### ISSUE TITLE
Deletion in Progress on Gradebook

### ISSUE THREAD

**Issue by lamerock** [antiquesprideeduph/eskUelA#2]
Possible cron job issue.

**Troubleshooting Done:**

Refered to:
https://docs.moodle.org/38/en/Cron_with_Windows_OS

**Status**
Solved

**Comment by racpsy** [comment]
have you tried CRON?

**Comment by jhingvp** [comment]
Sir G, is this resolved already?

**Comment by lamerock** [comment]
Resolved na ja sir. Ma update pa ko ka solution na.
